// Token type
export const SET_TOKEN = 'SET_TOKEN';

// Connection type
export const SET_CONNECTION = 'SET_CONNECTION';

// User types
export const SET_USER_ID = 'SET_USER_ID';
export const SET_USER_AVATAR = 'SET_USER_AVATAR';
export const SET_USER_TEMP_AVATAR = 'SET_USER_TEMP_AVATAR';
export const SET_USER_FULL_NAME = 'SET_USER_FULL_NAME';
export const SET_USER_EMAIL = 'SET_USER_EMAIL';
export const SET_USER_AUTHORITY = 'SET_USER_AUTHORITY';
export const SET_USER_DEVICE_BRAND = 'SET_USER_DEVICE_BRAND';
export const SET_USER_DEVICE_MODEL = 'SET_USER_DEVICE_MODEL';
export const SET_USER_DEVICE_OS_VERSION = 'SET_USER_DEVICE_OS_VERSION';

// Settings types
export const SET_SETTINGS_APP_NAME = 'SET_SETTINGS_APP_NAME';
export const SET_SETTINGS_APP_VERSION = 'SET_SETTINGS_APP_VERSION';
export const SET_SETTINGS_ASSETS_URL = 'SET_SETTINGS_ASSETS_URL';
export const SET_SETTINGS_SHARE_APP_TEXT = 'SET_SETTINGS_SHARE_APP_TEXT';
export const SET_SETTINGS_DOWNLOAD_URL = 'SET_SETTINGS_DOWNLOAD_URL';
export const SET_SETTINGS_DOWNLOAD_REF_URL = 'SET_SETTINGS_DOWNLOAD_REF_URL';
export const SET_SETTINGS_SHARE_TEXT = 'SET_SETTINGS_SHARE_TEXT';
export const SET_SETTINGS_PASSWORD_RESET_URL =
    'SET_SETTINGS_PASSWORD_RESET_URL';
export const SET_SETTINGS_USER_ACCOUNT_URL = 'SET_SETTINGS_USER_ACCOUNT_URL';
export const SET_SETTINGS_HELP_URL = 'SET_SETTINGS_HELP_URL';
export const SET_SETTINGS_USERAGENT = 'SET_SETTINGS_USERAGENT';
